# Generated by Django 2.2.16 on 2022-04-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220421_1234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscriber',
        ),
    ]
